# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia: 1.0.5
notifications:
  email: false
# uncomment the following lines to override the default test script
env:
    global:
    - PYTHON=conda
    matrix:
    - MPMATH=true
    - MPMATH=false
notifications:
  email: false
before_install:
    #install mpmath to test functionallity
  - if [ $MPMATH = "true" ]; then julia -e 'using Pkg; Pkg.add("Conda"); using Conda; Conda.add("mpmath")';fi  
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.test("FE"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("FE")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("FE")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
