name = "FE"
uuid = "98344202-5a1c-56b1-83aa-57a11ac3493f"
authors=["Nicolae Cindea <Nicolae.Cindea@uca.fr>"]
version = "0.1.1"

[compat]
julia = "1 - 1.5.3"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "Test"]
